name: Build and Maybe Deploy
on:
  push:
    branches:
      - '*'
    # Note this is NOT REGEX - see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    tags:
      - '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9]+'
jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10.x' # Build on target deploy version

    # Use caching to speed reload
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('package.json') }}
        restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}

    - name: Install Dependencies
      run: |
        npm ci

    # Log versions to help debug builds
    - name: Show Versions
      run: |
        echo "npm $(npm --version)"
        echo "node: $(node --version)"
        echo "gcloud: $(gcloud --version)"

    - name: Build
      run: |
        npm run build

    - name: Auth to Dev
      #if: github.ref == 'refs/heads/master'
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: 'mabl-dev'
        service_account_key: ${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT_MABL_DEV }}

    - name: Deploy to Dev
      #if: github.ref == 'refs/heads/master'
      run: gcloud functions deploy ${{ secrets.WEBHOOK_NAME }} --runtime nodejs10 --trigger-http --update-labels "app_hash=${{ github.sha}},app_name=handle_plan_webhook" --project=mabl-dev --entry-point=handlePlanWebhook --region us-central1 --allow-unauthenticated --set-env-vars=GCP_PROJECT=mabl-dev

    - name: Auth to Prod
      if: contains(github.ref, 'refs/tags/')
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: 'mabl-prod'
        service_account_key: ${{ secrets.GCP_DEPLOY_SERVICE_ACCOUNT_MABL_PROD }}

    - name: Deploy to Prod
      if: contains(github.ref, 'refs/tags/')
      run: gcloud functions deploy ${{ secrets.WEBHOOK_NAME }} --runtime nodejs10 --trigger-http --update-labels "app_hash=${{ github.sha}},app_name=handle_plan_webhook" --project=mabl-prod --entry-point=handlePlanWebhook --region us-central1 --allow-unauthenticated --set-env-vars=GCP_PROJECT=mabl-prod
