on: 
  push:
    tags:
    - '[0-9]+-[0-9]+-[0-9]+.[0-9]+'
  jobs:
    deploy-prod:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps: 
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
        version: '274.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL_PROD }}
        service_account_key: ${{ secrets.GCP_SA_KEY_PROD }}
    - run: gcloud functions deploy ${{ secrets.WEBHOOK_NAME }} --runtime nodejs10 --trigger-http