name: build_and_deploy_dev
on:
  push:
    branches:
      - master
    paths:
      - "**.ts"
      - "package.json"
      - ".github/workflows/deploy-dev.yaml"
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "274.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
      - run: gcloud functions deploy ${{ secrets.WEBHOOK_NAME }} --runtime nodejs8 --trigger-http --update-labels "app_hash=${{ github.sha}},app_name=handle_plan_webhook" --project=mabl-dev --entry-point=handlePlanWebhook --allow-unauthenticated
