name: build_and_deploy
on: 
  push:
    branches:
    - master
    paths:
    - '**.ts'
    - 'package.json'
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    with:
        version: '274.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL_DEV }}
        service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
    - run: gcloud functions deploy ${{ secrets.WEBHOOK_NAME }} --runtime nodejs10 --trigger-http
    
    

