name: build_and_deploy_dev
on:
  push:
    branches:
      - '*' 
      #- master
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud
        with:
          project_id: 'mabl-dev'
          service_account_key: ${{ secrets.gcp_sa_key_dev }}
      - run: gcloud functions deploy ${{ secrets.WEBHOOK_NAME }} --runtime nodejs8 --trigger-http --update-labels "app_hash=${{ github.sha}},app_name=handle_plan_webhook" --project=mabl-dev --entry-point=handlePlanWebhook --region us-central1 --allow-unauthenticated
